### ISSUE TITLE
Is there any demo etc?

### ISSUE THREAD

**Issue by bloggervista** [imzeeshan/laramovies#1]
Or atleast I guess screenshot would be really useful

Thanks for this awesome work

**Comment by imzeeshan** [comment]
No demo yet, here are some screenshots.

![movies-dashboard](https://user-images.githubusercontent.com/243183/41915297-fcfbf14e-7972-11e8-9a8c-dddd1cd9518c.png)
![users-edit](https://user-images.githubusercontent.com/243183/41915300-0119ad8e-7973-11e8-8f0b-54103a2230f5.png)
![movies-create](https://user-images.githubusercontent.com/243183/41915304-031648cc-7973-11e8-9b36-446e34bb502d.png)
![movies-api](https://user-images.githubusercontent.com/243183/41915342-19f60f5a-7973-11e8-9b62-26de3d345b0d.png)
![users-api](https://user-images.githubusercontent.com/243183/41915354-2138d540-7973-11e8-8e64-02e4591c0b20.png)

**Comment by bloggervista** [comment]
@imzeeshan Thank You. 

I guess we should keep it in screenshot folders or like that so it will be useful for other users also 🗡
